package com.prodeng.idsol.dao.mapper;

import com.prodeng.idsol.dao.entity.Ststockitemstatus;
import org.apache.ibatis.annotations.*;
import java.util.List;

public interface StstockitemstatusMapper{

	@Select ("SELECT * FROM ststockitemstatus")
	List<Ststockitemstatus> getAllStstockitemstatus();

	@Select ("SELECT * FROM ststockitemstatus WHERE ItemCode = #{itemCode} AND ReferenceNo = #{referenceNo} AND ProcessedState = #{processedState} ")
	Ststockitemstatus getStstockitemstatus(@Param("itemCode") String itemCode, @Param("referenceNo") String referenceNo, @Param("processedState") String processedState);

	@Insert ("INSERT INTO ststockitemstatus(ItemCode, ReferenceNo, ProcessedState, InwardQty, MIRQty, MRNQty, IssQty, RecQty, DCCQty, DCRQty, DCNRQty, OpeningBalance, CurrentStock, MovAvgPrice, AprInward, MayInward, JunInward, JulInward, AugInward, SepInward, OctInward, NovInward, DecInward, JanInward, FebInward, MarInward, AprMIR, MayMIR, JunMIR, JulMIR, AugMIR, SepMIR, OctMIR, NovMIR, DecMIR, JanMIR, FebMIR, MarMIR, AprMRN, MayMRN, JunMRN, JulMRN, AugMRN, SepMRN, OctMRN, NovMRN, DecMRN, JanMRN, FebMRN, MarMRN, AprIss, MayIss, JunIss, JulIss, AugIss, SepIss, OctIss, NovIss, DecIss, JanIss, FebIss, MarIss, AprRec, MayRec, JunRec, JulRec, AugRec, SepRec, OctRec, NovRec, DecRec, JanRec, FebRec, MarRec, AprDcc, MayDcc, JunDcc, JulDcc, AugDcc, SepDcc, OctDcc, NovDcc, DecDcc, JanDcc, FebDcc, MarDcc, AprDcr, MayDcr, JunDcr, JulDcr, AugDcr, SepDcr, OctDcr, NovDcr, DecDcr, JanDcr, FebDcr, MarDcr, AprDcnr, MayDcnr, JunDcnr, JulDcnr, AugDcnr, SepDcnr, OctDcnr, NovDcnr, DecDcnr, JanDcnr, FebDcnr, MarDcnr, AprOB, MayOB, JunOB, JulOB, AugOB, SepOB, OctOB, NovOB, DecOB, JanOB, FebOB, MarOB)  VALUES (#{itemCode} , #{referenceNo} , #{processedState} , #{inwardQty} , #{mIRQty} , #{mRNQty} , #{issQty} , #{recQty} , #{dCCQty} , #{dCRQty} , #{dCNRQty} , #{openingBalance} , #{currentStock} , #{movAvgPrice} , #{aprInward} , #{mayInward} , #{junInward} , #{julInward} , #{augInward} , #{sepInward} , #{octInward} , #{novInward} , #{decInward} , #{janInward} , #{febInward} , #{marInward} , #{aprMIR} , #{mayMIR} , #{junMIR} , #{julMIR} , #{augMIR} , #{sepMIR} , #{octMIR} , #{novMIR} , #{decMIR} , #{janMIR} , #{febMIR} , #{marMIR} , #{aprMRN} , #{mayMRN} , #{junMRN} , #{julMRN} , #{augMRN} , #{sepMRN} , #{octMRN} , #{novMRN} , #{decMRN} , #{janMRN} , #{febMRN} , #{marMRN} , #{aprIss} , #{mayIss} , #{junIss} , #{julIss} , #{augIss} , #{sepIss} , #{octIss} , #{novIss} , #{decIss} , #{janIss} , #{febIss} , #{marIss} , #{aprRec} , #{mayRec} , #{junRec} , #{julRec} , #{augRec} , #{sepRec} , #{octRec} , #{novRec} , #{decRec} , #{janRec} , #{febRec} , #{marRec} , #{aprDcc} , #{mayDcc} , #{junDcc} , #{julDcc} , #{augDcc} , #{sepDcc} , #{octDcc} , #{novDcc} , #{decDcc} , #{janDcc} , #{febDcc} , #{marDcc} , #{aprDcr} , #{mayDcr} , #{junDcr} , #{julDcr} , #{augDcr} , #{sepDcr} , #{octDcr} , #{novDcr} , #{decDcr} , #{janDcr} , #{febDcr} , #{marDcr} , #{aprDcnr} , #{mayDcnr} , #{junDcnr} , #{julDcnr} , #{augDcnr} , #{sepDcnr} , #{octDcnr} , #{novDcnr} , #{decDcnr} , #{janDcnr} , #{febDcnr} , #{marDcnr} , #{aprOB} , #{mayOB} , #{junOB} , #{julOB} , #{augOB} , #{sepOB} , #{octOB} , #{novOB} , #{decOB} , #{janOB} , #{febOB} , #{marOB} )")
	void  saveStstockitemstatus(Ststockitemstatus ststockitemstatus);

	@Update ("UPDATE  ststockitemstatus SET InwardQty = #{inwardQty}, MIRQty = #{mIRQty}, MRNQty = #{mRNQty}, IssQty = #{issQty}, RecQty = #{recQty}, DCCQty = #{dCCQty}, DCRQty = #{dCRQty}, DCNRQty = #{dCNRQty}, OpeningBalance = #{openingBalance}, CurrentStock = #{currentStock}, MovAvgPrice = #{movAvgPrice}, AprInward = #{aprInward}, MayInward = #{mayInward}, JunInward = #{junInward}, JulInward = #{julInward}, AugInward = #{augInward}, SepInward = #{sepInward}, OctInward = #{octInward}, NovInward = #{novInward}, DecInward = #{decInward}, JanInward = #{janInward}, FebInward = #{febInward}, MarInward = #{marInward}, AprMIR = #{aprMIR}, MayMIR = #{mayMIR}, JunMIR = #{junMIR}, JulMIR = #{julMIR}, AugMIR = #{augMIR}, SepMIR = #{sepMIR}, OctMIR = #{octMIR}, NovMIR = #{novMIR}, DecMIR = #{decMIR}, JanMIR = #{janMIR}, FebMIR = #{febMIR}, MarMIR = #{marMIR}, AprMRN = #{aprMRN}, MayMRN = #{mayMRN}, JunMRN = #{junMRN}, JulMRN = #{julMRN}, AugMRN = #{augMRN}, SepMRN = #{sepMRN}, OctMRN = #{octMRN}, NovMRN = #{novMRN}, DecMRN = #{decMRN}, JanMRN = #{janMRN}, FebMRN = #{febMRN}, MarMRN = #{marMRN}, AprIss = #{aprIss}, MayIss = #{mayIss}, JunIss = #{junIss}, JulIss = #{julIss}, AugIss = #{augIss}, SepIss = #{sepIss}, OctIss = #{octIss}, NovIss = #{novIss}, DecIss = #{decIss}, JanIss = #{janIss}, FebIss = #{febIss}, MarIss = #{marIss}, AprRec = #{aprRec}, MayRec = #{mayRec}, JunRec = #{junRec}, JulRec = #{julRec}, AugRec = #{augRec}, SepRec = #{sepRec}, OctRec = #{octRec}, NovRec = #{novRec}, DecRec = #{decRec}, JanRec = #{janRec}, FebRec = #{febRec}, MarRec = #{marRec}, AprDcc = #{aprDcc}, MayDcc = #{mayDcc}, JunDcc = #{junDcc}, JulDcc = #{julDcc}, AugDcc = #{augDcc}, SepDcc = #{sepDcc}, OctDcc = #{octDcc}, NovDcc = #{novDcc}, DecDcc = #{decDcc}, JanDcc = #{janDcc}, FebDcc = #{febDcc}, MarDcc = #{marDcc}, AprDcr = #{aprDcr}, MayDcr = #{mayDcr}, JunDcr = #{junDcr}, JulDcr = #{julDcr}, AugDcr = #{augDcr}, SepDcr = #{sepDcr}, OctDcr = #{octDcr}, NovDcr = #{novDcr}, DecDcr = #{decDcr}, JanDcr = #{janDcr}, FebDcr = #{febDcr}, MarDcr = #{marDcr}, AprDcnr = #{aprDcnr}, MayDcnr = #{mayDcnr}, JunDcnr = #{junDcnr}, JulDcnr = #{julDcnr}, AugDcnr = #{augDcnr}, SepDcnr = #{sepDcnr}, OctDcnr = #{octDcnr}, NovDcnr = #{novDcnr}, DecDcnr = #{decDcnr}, JanDcnr = #{janDcnr}, FebDcnr = #{febDcnr}, MarDcnr = #{marDcnr}, AprOB = #{aprOB}, MayOB = #{mayOB}, JunOB = #{junOB}, JulOB = #{julOB}, AugOB = #{augOB}, SepOB = #{sepOB}, OctOB = #{octOB}, NovOB = #{novOB}, DecOB = #{decOB}, JanOB = #{janOB}, FebOB = #{febOB}, MarOB = #{marOB} WHERE ItemCode = #{itemCode} AND ReferenceNo = #{referenceNo} AND ProcessedState = #{processedState} ")
	void  updateStstockitemstatus(@Param("itemCode") String itemCode, @Param("referenceNo") String referenceNo, @Param("processedState") String processedState);

	@Delete ("DELETE FROM ststockitemstatus WHERE ItemCode = #{itemCode} AND ReferenceNo = #{referenceNo} AND ProcessedState = #{processedState} ")
	void  deleteStstockitemstatus(@Param("itemCode") String itemCode, @Param("referenceNo") String referenceNo, @Param("processedState") String processedState);

    void updateStstockitemstatus(Ststockitemstatus ststockitemstatus);
}
