package com.prodeng.idsol.dao.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class Ststockitemstatus{

	@NonNull
	private String itemCode;
	@NonNull
	private String referenceNo;
	@NonNull
	private String processedState;
	private Double inwardQty;
	private Double mIRQty;
	private Double mRNQty;
	private Double issQty;
	private Double recQty;
	private Double dCCQty;
	private Double dCRQty;
	private Double dCNRQty;
	private Double openingBalance;
	private Double currentStock;
	private Double movAvgPrice;
	private Double aprInward;
	private Double mayInward;
	private Double junInward;
	private Double julInward;
	private Double augInward;
	private Double sepInward;
	private Double octInward;
	private Double novInward;
	private Double decInward;
	private Double janInward;
	private Double febInward;
	private Double marInward;
	private Double aprMIR;
	private Double mayMIR;
	private Double junMIR;
	private Double julMIR;
	private Double augMIR;
	private Double sepMIR;
	private Double octMIR;
	private Double novMIR;
	private Double decMIR;
	private Double janMIR;
	private Double febMIR;
	private Double marMIR;
	private Double aprMRN;
	private Double mayMRN;
	private Double junMRN;
	private Double julMRN;
	private Double augMRN;
	private Double sepMRN;
	private Double octMRN;
	private Double novMRN;
	private Double decMRN;
	private Double janMRN;
	private Double febMRN;
	private Double marMRN;
	private Double aprIss;
	private Double mayIss;
	private Double junIss;
	private Double julIss;
	private Double augIss;
	private Double sepIss;
	private Double octIss;
	private Double novIss;
	private Double decIss;
	private Double janIss;
	private Double febIss;
	private Double marIss;
	private Double aprRec;
	private Double mayRec;
	private Double junRec;
	private Double julRec;
	private Double augRec;
	private Double sepRec;
	private Double octRec;
	private Double novRec;
	private Double decRec;
	private Double janRec;
	private Double febRec;
	private Double marRec;
	private Double aprDcc;
	private Double mayDcc;
	private Double junDcc;
	private Double julDcc;
	private Double augDcc;
	private Double sepDcc;
	private Double octDcc;
	private Double novDcc;
	private Double decDcc;
	private Double janDcc;
	private Double febDcc;
	private Double marDcc;
	private Double aprDcr;
	private Double mayDcr;
	private Double junDcr;
	private Double julDcr;
	private Double augDcr;
	private Double sepDcr;
	private Double octDcr;
	private Double novDcr;
	private Double decDcr;
	private Double janDcr;
	private Double febDcr;
	private Double marDcr;
	private Double aprDcnr;
	private Double mayDcnr;
	private Double junDcnr;
	private Double julDcnr;
	private Double augDcnr;
	private Double sepDcnr;
	private Double octDcnr;
	private Double novDcnr;
	private Double decDcnr;
	private Double janDcnr;
	private Double febDcnr;
	private Double marDcnr;
	private Double aprOB;
	private Double mayOB;
	private Double junOB;
	private Double julOB;
	private Double augOB;
	private Double sepOB;
	private Double octOB;
	private Double novOB;
	private Double decOB;
	private Double janOB;
	private Double febOB;
	private Double marOB;
}
